import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wallper — Live Wallpapers for your Mac",
  description:
    "Wappler App brings you the best live wallpapers in one place. Unique animations, sleek design, and top-tier quality. We don’t follow trends — we set them.Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
